# Site settings
title: Ricky Chilcott
email: ricky@rickychilcott.com
description: "This is an awesome description"
baseurl: ""
url: "//www.rickychilcott.com"
github_username: rickychilcott
twitter_username: rickychilcott
facebook_username: rickychilcott

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]